from .views import PacienteListView
from .views import MedicoListView
from .views import PacienteCreateView
from .views import PersonaListView
from .views import PersonaLoginAdminView
from .views import PacienteSearchView
from .views import PersonaSearchView
from .views import PacienteDeleteView
from .views import MedicoCreateView
from .views import MedicoDeleteView
